language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - node
  - lts/*
  - 10
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "node" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
      chmod +x ./cc-test-reporter;
      ./cc-test-reporter before-build;
    fi;
script:
  - npm run coverage
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "node" ]]; then
      cat ./coverage/lcov.info | npx coveralls --verbose;
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi;
  - npm run clean:coverage
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_NODE_VERSION" == "node" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      npm run semantic-release;
    fi;